apiVersion: batch/v1
kind: CronJob
metadata:
  name: resource-quota-check
  namespace: kube-system
spec:
  schedule: "*/5 * * * *" # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resource-quota-check
            image: bitnami/kubectl:latest
            command: ["/bin/sh"]
            args: ["-c", "sh /scripts/resource_quota_check.sh"]
            env:
            - name: CRITICAL_INCREASE_LEVEL
              value: "30"  # Lower the critical increase level to see recommendations earlier
            - name: WARNING_INCREASE_LEVEL
              value: "20"  # Lower the warning increase level
            - name: INFO_INCREASE_LEVEL
              value: "10"  # Lower the info increase level
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          restartPolicy: OnFailure
          volumes:
          - name: scripts
            configMap:
              name: resource-quota-check-scripts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-quota-check-scripts
  namespace: kube-system
data:
  resource_quota_check.sh: |
    #!/bin/bash
    # Resource quota check script content from GitHub
    # Add the actual content of resource_quota_check.sh here