apiVersion: batch/v1
kind: CronJob
metadata:
  name: resource-quota-check
  namespace: kube-system
spec:
  schedule: "*/1 * * * *" # Run every x minutes
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300 # Keep jobs for 5 minutes after completion
      template:
        spec:
          containers:
          - name: resource-quota-check
            image: bitnami/kubectl:latest
            command: ["/bin/bash"] # Change to /bin/bash
            args: ["-c", "bash /scripts/resource_quota_check.sh"]
            env:
            - name: CRITICAL_INCREASE_LEVEL
              value: "30"
            - name: WARNING_INCREASE_LEVEL
              value: "20"
            - name: INFO_INCREASE_LEVEL
              value: "1"
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          restartPolicy: OnFailure
          volumes:
          - name: scripts
            configMap:
              name: resource-quota-check-scripts